### ISSUE TITLE
Bug reading Site URL from a posted callback

### ISSUE THREAD

**Issue by munjalpatel** [QuePort/passport-sharepoint#4]
Hello,

I have found a bug where the value for Site URL is being loaded from a posted form data.

    if(req != undefined && req.body && req.body.SPSiteUrl)
  	    spSiteUrl = req.query.SPSiteUrl;

`spSiteUrl = req.query.SPSiteUrl;` should be `spSiteUrl = req.body.SPSiteUrl;`

**Comment by S3bb1** [comment]
Fixed with Version 0.2.12
