### ISSUE TITLE
sslv3 alert handshake failure

### ISSUE THREAD

**Issue by siacomuzzi** [QuePort/passport-sharepoint#6]
Hi,

Since yesterday, I'm getting the following error:

```
DEBUG error: Error: 140658439763840:error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure:../deps/openssl/openssl/ssl/s23_clnt.c:762:

{
  "host":"{ME}.sharepoint.com",
  "port":443,
  "path":"/sites/{MY_SITE}/_api/web/currentuser",
  "method":"GET",
  "headers":{
    "Accept":"application/json;odata=verbose",
    "Authorization":"Bearer {MY_ACCESS_TOKEN}"},
    "agent":false,
    "ciphers":"RC4",
    "secureOptions":134217728
}
```

Looks like `RC4 cipher` is not supported anymore.

**Comment by siacomuzzi** [comment]
It works OK if I remove `ciphers` option from https://github.com/QuePort/passport-sharepoint/blob/master/lib/passport-sharepoint/strategy.js#L238

**Comment by S3bb1** [comment]
Hi @siacomuzzi 

we've looked into this problem and it seems like the RC4 Cipher isn't supported anymore. If you change this to 

    ciphers: 'ECDHE-RSA-AES256-SHA:AES256-SHA:RC4-SHA:RC4:HIGH:!MD5:!aNULL:!EDH:!AESGCM',
    honorCipherOrder: true

and remove the "agent" parameter, the authentication should work. 

See -> http://blog.mastykarz.nl/econnreset-error-connecting-office-365-nodejs/

we will change this and release a new version of passport-sharepoint

**Comment by siacomuzzi** [comment]
Thanks @S3bb1 !

Removing `ciphers` option works too. Do you have any concern with that?

**Comment by S3bb1** [comment]
fixed with above commit =)

**Comment by cayuu** [comment]
Thanks @S3bb1 - just a friendly reminder to `npm publish .` so it hits the registry :grinning: (ps. that open pull request for #4 gets a +1 from me - my O365 sharepoint.com setup doesn't work without that fix).

**Comment by S3bb1** [comment]
thx @cayuu ... merged the request. NPM publish will come today :)

**Comment by cayuu** [comment]
Many, many thanks for your efforts @S3bb1 - this library has been hugely helpful!

**Comment by S3bb1** [comment]
published @cayuu
